Source: https://www.practicaldatascience.org/html/exercises/Exercise_numpy.html

Cheat Sheet: https://datacamp-community-prod.s3.amazonaws.com/e9f83f72-a81b-42c7-af44-4e35b48b20b7

# Exercise 1

In [1]:
import numpy as np
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

# Exercise 2
What is the average value of the second column (to two decimal places)

In [6]:
random_integers[:,1].mean()

214895.8

# Exercise 3
What is the average value of the first 5 rows of the third and fourth columns?

In [14]:
random_integers[:5,2:4].mean()

286058.5

# Exercise 4
Close Python. On a piece of paper, write down the final result of the following code: <br>
`Expected result is [[2 4 6], [5 7 9]]`

In [15]:
import numpy as np
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

[[1 2 3]
 [4 5 6]]


In [17]:
second_matrix = np.array([1, 2, 3])
print(second_matrix)

[1 2 3]


In [18]:
first_matrix + second_matrix

array([[2, 4, 6],
       [5, 7, 9]])

# Exercise 5
Keep Python Closed! Write down the final result of the following code:

`Expected result is [2, 4, 6] (even numbers)`

In [19]:
my_vector = np.array([1, 2, 3, 4, 5, 6])
selection = my_vector % 2 == 0
my_vector[selection]

array([2, 4, 6])

# Exercise 6
Now open python and check your answers to Exercises 4 and 5.

# Working with Views

In [20]:
import numpy as np
my_array = np.array([1, 2, 3, 4])
my_array

array([1, 2, 3, 4])

In [21]:
my_slice = my_array[1:3]
my_slice

array([2, 3])

In [22]:
my_slice[0] = -1
my_slice

array([-1,  3])

In [23]:
my_array

array([ 1, -1,  3,  4])

This “view” behavior is entirely limited to numpy.

In [24]:
x = [1, 2, 3]
y = x[0:2]
y[0] = "a change"
y

['a change', 2]

In [25]:
x

[1, 2, 3]

## When do you get a view, and when do you get a copy?

Generally speaking:

- **you get a view if you do a plain, basic slice of an array**, and

- **the view remains a view if you edit it by modifying it using basic indexing (i.e. you use ``[]`` on the left side of the assignment operator).**

Outside of those two behaviors, you will usually get a copy.

In [26]:
# this slice will get you a view:

my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice[0] = -1
my_array

array([ 1, -1,  3])

In [29]:
# But if you use “fancy indexing” (where you pass a list when making your slice), you will NOT get a view:

my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]]
my_slice[0] = -1
my_array

array([1, 2, 3])

In [34]:
# if you modify a slice without using basic indexing, you get a copy, so changes won’t propagate:

my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice = my_slice * 2
my_slice

array([4, 6])

In [31]:
my_array

array([1, 2, 3])

In [32]:
# (If you want to do a full-array manipulation and preserve your view, always use square brackets on the left side of the assignment operator (=):

my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice[:] = my_slice * 2
my_slice

array([4, 6])

In [33]:
my_array

array([1, 4, 6])

**My advice on copies:** UNLESS YOU REALLY NEED A VIEW AND ARE BEING SUPER CAREFUL: don’t use views for anything but looking at data. If you ever want to modify or work with a sub-array, just make a copy to be safe. Computers are fast enough and ram is plentiful enough that for most applications, it’s almost never a problem.

# Exercise 7
Close your computer / laptop. Let’s try and work out a few problems in our heads to test our understanding of numpy views. Let’s start with the following array:

In [41]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [42]:
my_slice = my_array[:, 1:3]
my_slice

array([[2, 3],
       [5, 6]])

# Exercise 8
Now what does my_slice look like?

In [43]:
my_array[:, :] = my_array * 2 
my_slice

array([[ 4,  6],
       [10, 12]])

# Exercise 9
What does my_slice look like?

In [44]:
my_array = my_array * 2
my_slice

array([[ 4,  6],
       [10, 12]])

# Exercise 10
Stop, open Python, and try running these examples. Were your predictions correct? If not, why not?

# Exercise 11
OK, let’s close Python again and go back to pen and paper. Let’s also reset my_array and start over with the following code:

In [45]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [46]:
my_slice = my_array[:, 1:3].copy()
print(my_slice)

[[2 3]
 [5 6]]


Now suppose we run the following code: `my_array[:, :] = my_array * 2`. What does `my_slice` look like?

In [47]:
my_array[:, :] = my_array * 2
my_slice

array([[2, 3],
       [5, 6]])

Note: Don’t trust my_array.base¶
You will find some tutorials online that suggest you can test if one array is a view of another with the code my_slice.base is my_array. The problem is… this doesn’t always work. It does sometimes but not always.
<br>
The reason is that the .base property can be defined recursively. In this case, the slicing of my_array made my_array a view on data you can no longer access, so they actually do both point to the same data, but that data is not my_array, it’s my_array.base.